name: ember_flame
description: A Flutter Flame project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flame: ^1.8.0
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pj1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/images/bg_w.png"
  adaptive_icon_foreground: "assets/images/pj1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
