// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkJPx9Xx5MFf06KiJ8fe16xor6Plh4LA',
    appId: '1:659018838865:web:d1565830406ae5f03c5970',
    messagingSenderId: '659018838865',
    projectId: 'flame-ember',
    authDomain: 'flame-ember.firebaseapp.com',
    storageBucket: 'flame-ember.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDI-fJ5dGqcgMiKnnCxo0DqIN1UNKesAQ',
    appId: '1:659018838865:android:c1c5c42db14b948f3c5970',
    messagingSenderId: '659018838865',
    projectId: 'flame-ember',
    storageBucket: 'flame-ember.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoRZgMUnKZu_KVrSVPcSCmCufH4D1kJYs',
    appId: '1:659018838865:ios:25ec86c974f6bdc63c5970',
    messagingSenderId: '659018838865',
    projectId: 'flame-ember',
    storageBucket: 'flame-ember.appspot.com',
    iosClientId: '659018838865-kch0msak882eh0pdiqsu38sp5srmveof.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoRZgMUnKZu_KVrSVPcSCmCufH4D1kJYs',
    appId: '1:659018838865:ios:ae9c5d66017e65623c5970',
    messagingSenderId: '659018838865',
    projectId: 'flame-ember',
    storageBucket: 'flame-ember.appspot.com',
    iosClientId: '659018838865-k25pk9j3f3jniv0m3etetel1t9dm3kgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameDoc.RunnerTests',
  );
}
